# Generated by Django 3.0.8 on 2020-07-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_manage', '0002_product_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_ordered',
            new_name='date_created',
        ),
    ]
