# Generated by Django 3.0.8 on 2020-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manage', '0003_auto_20200723_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
