# Generated by Django 3.0.8 on 2020-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manage', '0005_auto_20200727_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
